name: Deploy ACA API
on:
  workflow_dispatch:

env:  
  RESOURCE_GROUP: "RG_Rugby_Stats_v2"
  LOCATION: "westeurope"
  APP_NAME_API: "rugbystats-api"
  CONTAINERAPPS_ENVIRONMENT_NAME: "RugbyStats-env"
  ACR_NAME: "rugbystatv2acr"
  IMAGE_VERSION: 1.0.0
  
jobs:
  deploy_aca_api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set Subscription
        run: |
          az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Installation extension containerapp
        run: |
          az extension add --name containerapp
          az extension add --name containerapp --upgrade
          az extension list -o table 
          az provider register --namespace Microsoft.App
          az provider register --namespace Microsoft.OperationalInsights
          az config set extension.use_dynamic_install=yes_without_prompt

      - name: Deploy Azure Container Apps
        run: |
          REGISTRY_PASSWORD=$(az acr credential show --name ${{ env.ACR_NAME }} -o tsv --query "passwords[0].value")
          az containerapp create \
            --name ${{ env.APP_NAME_API }} \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --environment ${{ env.CONTAINERAPPS_ENVIRONMENT_NAME }} \
            --image ${{ env.ACR_NAME }}.azurecr.io/${{ env.APP_NAME_API }}:${{ env.IMAGE_VERSION }} \
            --secrets secret-db-host=${{ secrets.POSTGRESQL_HOSTNAME }} secret-db-user=${{ secrets.POSTGRESQL_ADMINUSER }} secret-db-password=${{ secrets.POSTGRESQL_ADMINPASSWORD }} secret-db-database=${{ secrets.POSTGRESQL_DBNAME }} secret-db-port=${{ secrets.POSTGRESQL_PORT }} \
            --env-vars DB_HOST=secretref:secret-db-host DB_USER=secretref:secret-db-user DB_PASS=secretref:secret-db-password DB_NAME=secretref:secret-db-database DB_PORT=secretref:secret-db-port \
            --registry-username ${{ env.ACR_NAME }} \
            --registry-password $REGISTRY_PASSWORD \
            --cpu "0.75" \
            --memory "1.5Gi" \
            --min-replicas 3 \
            --max-replicas 10 \
            --target-port 3000 \
            --ingress 'external' \
            --query configuration.ingress.fqdn
