name: Deploy Infrastructure

on: workflow_dispatch

env:
  RESOURCE_GROUP: "RG_Rugby_Stats_v2"
  LOCATION: "westeurope"
  POSTGRESQL_SKUNAME: "Standard_B1ms"
  POSTGRESQL_TIER: "Burstable"
  POSTGRESQL_VERSION: "14"
  POSTGRESQL_STORAGESIZE: "32"
  ACR_NAME: "rugbystatv2acr"
  ACR_SKU: "Basic"
  LOG_ANALYTICS_NAME: "RugbyStaLa-env"
  CONTAINERAPPS_ENVIRONMENT_NAME: "RugbyStats-env"

jobs:
  deploy_infra_rg:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set Subscription
        run: |
          az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy Resource Group
        run: |
          az group create \
            --name ${{ env.RESOURCE_GROUP }} \
            --location ${{ env.LOCATION }}

  deploy_infra_postgreSQL:
    runs-on: ubuntu-latest
    needs: deploy_infra_rg
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set Subscription
        run: |
          az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy Flexible Server PostgreSQL
        run: |
          az postgres flexible-server create \
            --name ${{ secrets.POSTGRESQL_NAME }} \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --location ${{ env.LOCATION }} \
            --admin-user ${{ secrets.POSTGRESQL_ADMINUSER }} \
            --admin-password ${{ secrets.POSTGRESQL_ADMINPASSWORD }} \
            --sku-name ${{ env.POSTGRESQL_SKUNAME }} \
            --tier ${{ env.POSTGRESQL_TIER }} \
            --version ${{ env.POSTGRESQL_VERSION }} \
            --storage-size ${{ env.POSTGRESQL_STORAGESIZE }} \
            --public-access 0.0.0.0 --yes

          az postgres flexible-server firewall-rule create \
            --name ${{ secrets.POSTGRESQL_NAME }} \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --rule-name allowall \
            --start-ip-address 0.0.0.0 \
            --end-ip-address 255.255.255.255

          az config set extension.use_dynamic_install=yes_without_prompt
          az postgres flexible-server parameter set \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --server-name ${{ secrets.POSTGRESQL_NAME }} \
            --name require_secure_transport --value off

          az postgres flexible-server db create \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --server-name ${{ secrets.POSTGRESQL_NAME }} \
            --database-name ${{ secrets.POSTGRESQL_DBNAME }}
          
          az postgres flexible-server execute \
            --admin-password ${{ secrets.POSTGRESQL_ADMINPASSWORD }} \
            --admin-user ${{ secrets.POSTGRESQL_ADMINUSER }} \
            --name ${{ secrets.POSTGRESQL_NAME }} \
            --database-name ${{ secrets.POSTGRESQL_DBNAME }} \
            --file-path ./DB/create_tables.sql

  deploy_infra_acr:
    runs-on: ubuntu-latest
    needs: deploy_infra_rg
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set Subscription
        run: |
          az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy Infrastructure
        run: |
          az acr create \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --name ${{ env.ACR_NAME }} \
            --sku ${{ env.ACR_SKU }} \
            --admin-enabled true

  deploy_infra_environment:
    runs-on: ubuntu-latest
    needs: deploy_infra_rg
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set Subscription
        run: |
          az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Installation extension containerapp
        run: |
          az extension add --name containerapp
          az extension add --name containerapp --upgrade
          az extension list -o table 
          az provider register --namespace Microsoft.App
          az provider register --namespace Microsoft.OperationalInsights
          az config set extension.use_dynamic_install=yes_without_prompt

      - name: Deploy Environment
        run: |
          az monitor log-analytics workspace create \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --workspace-name ${{ env.LOG_ANALYTICS_NAME }} \
            --location ${{ env.LOCATION }}
          LOG_ANALYTICS_WORKSPACE_CLIENT_ID=`az monitor log-analytics workspace show --query customerId -g ${{ env.RESOURCE_GROUP }} -n ${{ env.LOG_ANALYTICS_NAME }} --out tsv`
          LOG_ANALYTICS_WORKSPACE_PRIMARY_KEY=`az monitor log-analytics workspace get-shared-keys --query primarySharedKey -g ${{ env.RESOURCE_GROUP }} -n ${{ env.LOG_ANALYTICS_NAME }} --out tsv`
          az containerapp env create \
            --name ${{ env.CONTAINERAPPS_ENVIRONMENT_NAME }} \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --location ${{ env.LOCATION }} \
            --logs-workspace-id $LOG_ANALYTICS_WORKSPACE_CLIENT_ID \
            --logs-workspace-key $LOG_ANALYTICS_WORKSPACE_PRIMARY_KEY

