name: Deploy Infrastructure

on: workflow_dispatch

env:
  RESOURCE_GROUP: "RG_Rugby_Stats_v2"
  LOCATION: "westeurope"
  POSTGRESQL_NAME: "rugbystatsv2"
  POSTGRESQL_ADMINUSER: "adminDB"
  POSTGRESQL_ADMINPASSWORD: "Password123$"
  POSTGRESQL_SKUNAME: "Standard_B1ms"
  POSTGRESQL_TIER: "Burstable"
  POSTGRESQL_VERSION: "14"
  POSTGRESQL_STORAGESIZE: "32"
  POSTGRESQL_DBNAME: "rugby_api"
  ACR_NAME: "rugbystatv2acr"
  ACR_SKU: "Basic"


jobs:
  deploy_infra_rg:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set Subscription
        run: |
          az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy Resource Group
        run: |
          az group create \
            --name ${{ env.RESOURCE_GROUP }} \
            --location ${{ env.LOCATION }}

  deploy_infra_postgreSQL:
    runs-on: ubuntu-latest
    needs: deploy_infra_rg
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set Subscription
        run: |
          az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy Flexible Server PostgreSQL
        run: |
          az postgres flexible-server create \
            --name ${{ env.POSTGRESQL_NAME }} \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --location ${{ env.LOCATION }} \
            --admin-user ${{ env.POSTGRESQL_ADMINUSER }} \
            --admin-password ${{ env.POSTGRESQL_ADMINPASSWORD }} \
            --sku-name ${{ env.POSTGRESQL_SKUNAME }} \
            --tier ${{ env.POSTGRESQL_TIER }} \
            --version ${{ env.POSTGRESQL_VERSION }} \
            --storage-size ${{ env.POSTGRESQL_STORAGESIZE }} \
            --public-access 0.0.0.0 --yes

          az postgres flexible-server firewall-rule create \
            --name ${{ env.POSTGRESQL_NAME }} \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --rule-name allowall \
            --start-ip-address 0.0.0.0 \
            --end-ip-address 255.255.255.255

          az config set extension.use_dynamic_install=yes_without_prompt
          az postgres flexible-server parameter set \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --server-name ${{ env.POSTGRESQL_NAME }} \
            --name require_secure_transport --value off

          az postgres flexible-server db create \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --server-name ${{ env.POSTGRESQL_NAME }} \
            --database-name ${{ env.POSTGRESQL_DBNAME }}
          
          az postgres flexible-server execute \
            --admin-password ${{ env.POSTGRESQL_ADMINPASSWORD }} \
            --admin-user ${{ env.POSTGRESQL_ADMINUSER }} \
            --name ${{ env.POSTGRESQL_NAME }} \
            --database-name ${{ env.POSTGRESQL_DBNAME }} \
            --file-path ./DB/create_tables.sql

  deploy_infra_acr:
    runs-on: ubuntu-latest
    needs: deploy_infra_rg
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set Subscription
        run: |
          az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy Infrastructure
        run: |
          az acr create \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --name ${{ env.ACR_NAME }} \
            --sku ${{ env.ACR_SKU }} \
            --admin-enabled true





        
          
